window.ability=[
  ["ailment-remove","","Removes status ailments when moving to next map"],
  ["atk-combo",1.1,"Boosts ATK by 1.1x during combos"],
  ["atk-up",100,"Boosts ATK by 100"],
  ["atk-up",150,"Boosts ATK by 150"],
  ["atk-up",200,"Boosts ATK by 200"],
  ["atk-up",250,"Boosts ATK by 250"],
  ["atk-up",300,"Boosts ATK by 300"],
  ["atk-up",400,"Boosts ATK by 400"],
  ["atkdown-attack",10,"10% chance of ATK reduction for 4 turns when attacking"],
  ["atkdown-combo",10,"Combos have a 10% chance of ATK reduction for 4 turns"],
  ["atkdown-rate",10,"Boosts ATK reduction rate by 10%"],
  ["atkdown-rate",20,"Boosts ATK reduction rate by 20%"],
  ["atkdown-red",10,"Lowers chance of receiving ATK reduction by 10% (Not F Skills)"],
  ["atkdown-red",20,"Lowers chance of receiving ATK reduction by 20% (Not F Skills)"],
  ["atkdown-red",35,"Lowers chance of receiving ATK reduction by 35% (Not F Skills)"],
  ["barrier-destroy","","Removes barriers when attacking"],
  ["barrier-ignore","","Ignores barriers when attacking"],
  ["bod-red",10,"Reduces damage from BOD enemies by 10%"],
  ["bod-red",15,"Reduces damage from BOD enemies by 15%"],
  ["bod-red",25,"Reduces damage from BOD enemies by 25%"],
  ["bod-up",15,"Boosts damage against BOD enemies by 15%"],
  ["bod-up",20,"Boosts damage against BOD enemies by 20%"],
  ["bod-up",40,"Boosts damage against BOD enemies by 40%"],
  ["brv-red",10,"Reduces damage from BRV enemies by 10%"],
  ["brv-red",15,"Reduces damage from BRV enemies by 15%"],
  ["brv-red",20,"Reduces damage from BRV enemies by 20%"],
  ["brv-red",25,"Reduces damage from BRV enemies by 25%"],
  ["brv-up",15,"Boosts damage against BRV enemies by 15%"],
  ["brv-up",20,"Boosts damage against BRV enemies by 20%"],
  ["brv-up",30,"Boosts damage against BRV enemies by 30%"],
  ["brv-up",40,"Boosts damage against BRV enemies by 40%"],
  ["chakra-jutsu-0",10,"10% chance to reduce chakra consumed by Normal Jutsus to 0"],
  ["chakra-jutsu-0",15,"15% chance to reduce chakra consumed by Normal Jutsus to 0"],
  ["chakra-jutsu-0",20,"20% chance to reduce chakra consumed by Normal Jutsus to 0"],
  ["chakra-maprec",1,"Restores 1 chakra when moving to next map"],
  ["chakra-rec",5,"5% chance to restore 1 chakra when attacked"],
  ["chakra-red",1,"Reduces chakra gauge by 1"],
  ["chakra-ult-0",10,"10% chance to reduce chakra consumed by Ultimate Jutsus to 0"],
  ["chakra-ult-0",15,"15% chance to reduce chakra consumed by Ultimate Jutsus to 0"],
  ["chakra-ult-0",20,"20% chance to reduce chakra consumed by Ultimate Jutsus to 0"],
  ["chakraseal-red",20,"Lowers chance of being chakra recovery sealed by 20% (Not F Skills)"],
  ["chakraseal-red",30,"Lowers chance of being chakra recovery sealed by 30% (Not F Skills)"],
  ["counter-red",15,"Lowers chance of being countered by 15%"],
  ["crit-combo",1.75,"Boosts critical rate by 1.75x during combos"],
  ["crit-rate",1.5,"Boosts critical rate by 1.5x"],
  ["crit-rate",2,"Boosts critical rate by 2x"],
  ["crit-rate",2.5,"Boosts critical rate by 2.5x"],
  ["death-dmg",3000,"Deals 3000 fixed damage to enemy's front row upon death"],
  ["dmg-red",5,"Reduces damage taken by 5%"],
  ["dmg-red",10,"Reduces damage taken by 10%"],
  ["dmg-red",15,"Reduces damage taken by 15%"],
  ["dmg-red",20,"Reduces damage taken by 20%"],
  ["dmg-red",30,"Reduces damage taken by 30%"],
  ["dodge",5,"5% chance of dodging an attack"],
  ["dodge",10,"10% chance of dodging an attack"],
  ["dodge",15,"15% chance of dodging an attack"],
  ["dodge",20,"20% chance of dodging an attack"],
  ["effect-duration-up",1,"Extends status effect durations by 1 turn"],
  ["effect-duration-up",2,"Extends status effect durations by 2 turns"],
  ["effect-jutsu-up",2,"Extends status effect durations of Normal Jutsu by 2 turns"],
  ["effect-rate",10,"Boosts the rate of status ailments by 10%"],
  ["effect-ult-up",1,"Extends status effect durations of Ultimate Jutsu by 1 turn"],
  ["heal-up",100,"Increases healing amount on jutsus by 100"],
  ["heal-up",200,"Increases healing amount on jutsus by 200"],
  ["heal-up",300,"Increases healing amount on jutsus by 300"],
  ["heal-up",500,"Increases healing amount on jutsus by 500"],
  ["heal-up",1000,"Increases healing amount on jutsus by 1000"],
  ["hp-combo",100,"Restores 100 HP during combos"],
  ["hp-heal",100,"Restores 100 HP every turn"],
  ["hp-heal",200,"Restores 200 HP every turn"],
  ["hp-heal",250,"Restores 250 HP every turn"],
  ["hp-heal",300,"Restores 300 HP every turn"],
  ["hp-heal",350,"Restores 350 HP every turn"],
  ["hp-maprec",300,"Restores 300 HP when moving to next map"],
  ["hp-maprec",600,"Restores 600 HP when moving to next map"],
  ["hp-up",100,"Boosts HP by 100"],
  ["hp-up",150,"Boosts HP by 150"],
  ["hp-up",200,"Boosts HP by 200"],
  ["hpseal-red",20,"Lowers chance of being HP recovery sealed by 20% (Not F Skills)"],
  ["hpseal-red",30,"Lowers chance of being HP recovery sealed by 30% (Not F Skills)"],
  ["hpseal",10,"10% chance to seal HP recovery for 4 turns when attacking"],
  ["hrt-red",10,"Reduces damage from HRT enemies by 10%"],
  ["hrt-red",15,"Reduces damage from HRT enemies by 15%"],
  ["hrt-red",25,"Reduces damage from HRT enemies by 25%"],
  ["hrt-up",10,"Boosts damage against HRT enemies by 10%"],
  ["hrt-up",20,"Boosts damage against HRT enemies by 20%"],
  ["hrt-up",40,"Boosts damage against HRT enemies by 40%"],
  ["immob-rate",10,"Boosts immobilization rate by 10%"],
  ["immob-rate",20,"Boosts immobilization rate by 20%"],
  ["immob-red",10,"Lowers chance of being immobilized by 10% (Not F Skills)"],
  ["immob-red",15,"Lowers chance of being immobilized by 15% (Not F Skills)"],
  ["immob-red",20,"Lowers chance of being immobilized by 20% (Not F Skills)"],
  ["immob-red",25,"Lowers chance of being immobilized by 25% (Not F Skills)"],
  ["immob-red",30,"Lowers chance of being immobilized by 30% (Not F Skills)"],
  ["jutsu-aoe","","Normal Jutsu hits all enemies in range"],
  ["jutsu-multi",1,"Increases multipler of Normal Jutsu by 1"],
  ["multi-up",1,"Increases multipler of both jutsus by 1"],
  ["multi-up",2,"Increases multipler of both jutsus by 2"],
  ["pc-chakra",1,"Start with 1 extra chakra in Phantom Castle"],
  ["seal-rate",10,"Boosts jutsu sealing rate by 10%"],
  ["seal-rate",20,"Boosts jutsu sealing rate by 20%"],
  ["seal-red",10,"Lowers chance of being jutsu sealed by 10% (Not F Skills)"],
  ["seal-red",15,"Lowers chance of being jutsu sealed by 15% (Not F Skills)"],
  ["seal-red",20,"Lowers chance of being jutsu sealed by 20% (Not F Skills)"],
  ["seal-red",25,"Lowers chance of being jutsu sealed by 25% (Not F Skills)"],
  ["seal-red",30,"Lowers chance of being jutsu sealed by 30% (Not F Skills)"],
  ["seal-red",35,"Lowers chance of being jutsu sealed by 35% (Not F Skills)"],
  ["skl-red",10,"Reduces damage from SKL enemies by 10%"],
  ["skl-red",15,"Reduces damage from SKL enemies by 15%"],
  ["skl-red",20,"Reduces damage from SKL enemies by 20%"],
  ["skl-red",25,"Reduces damage from SKL enemies by 25%"],
  ["skl-up",15,"Boosts damage against SKL enemies by 15%"],
  ["skl-up",30,"Boosts damage against SKL enemies by 30%"],
  ["skl-up",40,"Boosts damage against SKL enemies by 40%"],
  ["slip-attack",],
  ["slip-combo",10,"10% chance of slip damage for 4 turns during combos"],
  ["slip-rate",10,"Boosts slip damage rate by 10%"],
  ["slip-rate",15,"Boosts slip damage rate by 15%"],
  ["slip-rate",20,"Boosts slip damage rate by 20%"],
  ["slip-red",10,"Lowers chance of receiving slip damage by 10% (Not F Skills)"],
  ["slip-red",15,"Lowers chance of receiving slip damage by 15% (Not F Skills)"],
  ["slip-red",20,"Lowers chance of receiving slip damage by 20% (Not F Skills)"],
  ["slip-red",35,"Lowers chance of receiving slip damage by 35% (Not F Skills)"],
  ["spd-up",20,"Boosts SPD by 20"],
  ["spd-up",30,"Boosts SPD by 30"],
  ["substitution-ignore","","Ignores substitution"],
  ["type-null","","Nullifies type disadvantange when attacking"],
  ["ult-aoe","","Ultimate Jutsu hits all enemies in range"],
  ["ult-multi-up",1,"Increases multipler of Ultimate Jutsu by 1"],
  ["ult-multi-up",2,"Increases multipler of Ultimate Jutsu by 2"],
  ["wis-red",10,"Reduces damage from WIS enemies by 10%"],
  ["wis-red",15,"Reduces damage from WIS enemies by 15%"],
  ["wis-red",20,"Reduces damage from WIS enemies by 20%"],
  ["wis-red",25,"Reduces damage from WIS enemies by 25%"],
  ["wis-up",15,"Boosts damage against WIS enemies by 15%"],
  ["wis-up",20,"Boosts damage against WIS enemies by 20%"],
  ["wis-up",40,"Boosts damage against WIS enemies by 40%"]
]
