window.chara=[
	{
    "id": 1,
    "assetid": "00239",
    "name": "Naruto Uzumaki",
    "subname": "The Worst Loser",
    "affi": "leaf",
    "type": "hrt",
    "cost": 4,
    "rarity": 3,
		"maxlv": 30,
		"limitbreak": 0,
    "chakra": 5,
		"range": "Mid",
		"hp": 380,
    "atk": 322,
		"pvphp": 7980,
		"pvpatk": 580,
    "pvpspd": 108,
    "field": "Boosts ATK by 65 - 130",
    "buddy": "Boosts ATK by 50",
    "ability1": "atk-combo",
    "ability1desc": 1.1,
    "ability2": "hp-maprec",
    "ability2desc": 300,
    "ability3": "hp-up",
    "ability3desc": 100,
    "pvpability1": "atk-combo",
    "pvpability1desc": 1.1,
    "pvpability2": "hp-maprec",
    "pvpability2desc": 300,
    "pvpability3": "hp-up",
    "pvpability3desc": 500,
    "hit0": "1",
		"hit1": "4",
		"hit2": "8",
		"target1": "2",
		"jutsu": "Evil Wind Shuriken: Shadow Windmill",
    "jutsudesc": "2.2x ATK in HRT damage to all enemies in range.",
    "jutsupvp": "2.2x ATK in HRT damage to all enemies in range.",
		"sync1": "mid",
    "sync1desc": "atk",
		"sync1value": 50,
}
]
