window.chara=[
	{
    "id": "1",
    "assetid": "00003",
    "name": "Naruto Uzumaki",
    "subname": "The Worst Loser",
    "affi": "leaf",
    "type": "hrt",
    "cost": "4",
    "rarity": "3",
    "limitbreak": "0",
    "chakra": "5",
    "hp": "380",
    "lbhp": "",
    "pvphp": "7980",
    "atk": "322",
    "lbatk": "",
    "pvpatk": "580",
    "pvpspd": "108",
    "range": "Mid",
    "field": "Boosts ATK by 65 - 130",
    "buddy": "Boosts ATK by 50",
    "ability1": "atk-combo",
    "ability1desc": "1.1",
    "ability2": "hp-maprec",
    "ability2desc": "300",
    "ability3": "hp-up",
    "ability3desc": "100",
    "ability4": "",
    "ability4desc": "",
    "ability5": "",
    "ability5desc": "",
    "ability6": "",
    "ability6desc": "",
    "ability1pvp": "atk-combo",
    "ability1descpvp": "1.1",
    "ability2pvp": "hp-maprec",
    "ability2descpvp": "300",
    "ability3pvp": "hp-up",
    "ability3descpvp": "500",
    "ability4pvp": "",
    "ability4descpvp": "",
    "ability5pvp": "",
    "ability5descpvp": "",
    "ability6pvp": "",
    "ability6descpvp": "",
    "hit0": "1",
    "skill1": "Evil Wind Shuriken: Shadow Windmill",
    "skill1desc": "2.2x ATK in HRT damage to all enemies in range.",
    "skill1pvp": "2.2x ATK in HRT damage to all enemies in range.",
    "target1": "2",
    "hit1": "4",
    "skill2": "",
    "skill2desc": "",
    "skill2pvp": "",
    "target2": "",
    "hit2": "",
    "sync1": "Sync with Leaf",
    "sync1desc": "Boosts ATK by 50",
    "sync2": "-",
    "sync2desc": "",
    "sync3": "-",
    "sync3desc": "",
    "evo1": "hrt-scroll1",
    "evo2": "hrt-scroll1",
    "evo3": "hrt-scroll1",
    "evo4": "",
    "evo5": "",
    "obtained": "Story 07-04",
}
]
