window.fb = [
  {
    'fixed-dmg': 'Deals [x] fixed damage',
    'counter': '[x]% chance to counter-attack when hit',
    'counter-red': 'Lowers chance of being countered by [x]%',
    'atk': 'Boosts ATK by [x]',
    'spd': 'Boosts SPD by [x]',
    'sub': 'Ignores Substitution when attacking',
    'crit': 'Boosts critical rate by [x]x',
    'dmg-red': 'Reduces damage taken by [x]%',
    'hp-heal': 'Restores [x] HP',
    'dodge': '[x]% chance of dodging an attack (Not Slip Damage)',
    'sub-red': 'Reduces chance of enemy using substitution jutsu by [x]%',
    'hrt-atk': 'Boosts ATK of HRT units by [x]%',
    'skl-atk': 'Boosts ATK of SKL units by [x]%',
    'bod-atk': 'Boosts ATK of BOD units by [x]%',
    'brv-atk': 'Boosts ATK of BRV units by [x]%',
    'wis-atk': 'Boosts ATK of WIS units by [x]%',
    'hrt-red': 'Reduces damage from HRT enemies by [x]%',
    'skl-red': 'Reduces damage from SKL enemies by [x]%',
    'bod-red': 'Reduces damage from BOD enemies by [x]%',
    'brv-red': 'Reduces damage from BRV enemies by [x]%',
    'wis-red': 'Reduces damage from WIS enemies by [x]%',
    'multi-up': 'Increases multiplier of both jutsus by [x]',
    'atkdown-red': 'Lowers chance of receiving ATK reduction by [x]% (Not F Skills)',
    'immob-red': 'Lowers chance of being immobilized by [x]% (Not F Skills)',
    'seal-red': 'Lowers chance of being jutsu sealed by [x]% (Not F Skills)',
    'slip-red': 'Lowers chance of receiving slip damage by [x]% (Not F Skills)',
    'chakraseal-red': 'Lowers chance of being chakra recovery sealed by [x]% (Not F Skills)',
    'switchseal-red': 'Lowers chance of being switch sealed by [x]% (Not F Skills)',
    'immob-null': 'Nullifies Immobilization (Excluding Field Effects and F Skills)',
    'jutsu-null': 'Nullifies Jutsu Sealing (Excluding Field Effects and F Skills)'
  }
]
