window.sync = [
  {
    //sync with
    'short': 'Short Range',
    'mid': 'Mid Range',
    'long': 'Long Range',
    'shortlong': 'Short and Long Range',
    'shortmid': 'Short and Mid Range',
    'midlong': 'Mid and Long Range',
    'nonshort': 'all but Short Range',
    'nonmid': 'all but Mid Range',
    'nonlong': 'all but Long Range',
    'hrt': 'HRT',
    'skl': 'SKL',
    'bod': 'BOD',
    'brv': 'BRV',
    'wis': 'WIS',
    'hrtsklbod': 'HRT, SKL and BOD',
    'brvwis': 'BRV and WIS',
    'nonhrt': 'all but HRT',
    'nonskl': 'all but SKL',
    'nonbod': 'all but BOD',
    'nonbrv': 'all but BRV',
    'nonwis': 'all but WIS',
    'leaf': 'Hidden Leaf',
    'mist': 'Mist',
    'sand': 'Sand',
    'sound': 'Sound',
    'cloud': 'Cloud',
    'rain': 'Rain',
    'taka': 'Taka',
    'akatsuki': 'Akatasuki',
    'senju': 'Senju Clan',
    'uchiha': 'Uchiha Clan',
    'ninja': 'Ninja Alliance',

    //descriptions
    'atk': 'Boosts ATK by [x]',
    'sub': 'Ignores Substitution when attacking',
    'crit': 'Boosts critical rate by [x]x',
    'dmg-red': 'Reduces damage taken by [x]%',
    'hp-heal': 'Restores [x] HP every turn',
    'dodge': '[x]% chance of dodging an attack (Not Slip Damage)',
    'hrt-red': 'Reduces damage from HRT enemies by [x]%',
    'skl-red': 'Reduces damage from SKL enemies by [x]%',
    'bod-red': 'Reduces damage from BOD enemies by [x]%',
    'brv-red': 'Reduces damage from BRV enemies by [x]%',
    'wis-red': 'Reduces damage from WIS enemies by [x]%',
    'multi-up': 'Increases multiplier of both jutsus by [x]',
    'atkdown-red': 'Lowers chance of receiving ATK reduction by [x]%',
    'immob-red': 'Lowers chance of being immobilized by [x]%',
    'seal-red': 'Lowers chance of being jutsu sealed by [x]%',
    'slip-red': 'Lowers chance of receiving slip damage by [x]%',
    'hpseal-red': 'Lowers chance of being HP recovery sealed by [x]%',
    'immob-null': 'Nullifies Immobilization (Excluding Field Effects and F Skills)',
    'jutsu-null': 'Nullifies Jutsu Sealing (Excluding Field Effects and F Skills)'
  }
]
